### ISSUE TITLE
Allow IBC Forwarder to be ticked directly

### ISSUE THREAD

**Issue by stiiifff** [timewave-computer/covenants#217]
It should be possible to tick the IBC Forwarder directly, not just from the Clock contract.

**Comment by stiiifff** [comment]
@uditvira We were discussing with @bekauz about various options, and the following idea came up: replace the CLOCK_ADDRESS by a ADMIN_ALLOW_LIST as an array of address. We would modify the covenant contract(s) to pass both the Clock & the top-level covenant's admin adresses, to allow either to tick the forwarder.
Ben also suggested to make that field an Option<T> so that when it's None, it basically means ticking is a permissionless operation (anyone allowed to tick).
We could also apply the same principles to other contracts .. as it doesn't seem too much work.
wdyt ?

**Comment by uditvira** [comment]
What does having a permissioned clock give us? It gives us some marginal UX improvements and pause functionality:
- it allows us to tick a single contract which ticks the other contracts in a round robin fashion
- it allows us to pause the clock, which in turn pauses ticking on all the other contracts, effectively pausing the entire covenant

I think we want at least two properties:
1. The option to tick the clock directly, i.e., validating the tick caller address where there is Some address present, and removing this validation when the address is None
2. Having some mechanism to pause each of the contracts, i.e., each of the contract has a  "Pause" function which disables ticking. The pause function can only called by the admin. We could then expose an admin "Pause" function at the top level covenant which can Pause all or specific underlying contracts

Can you say about why you want the clock address to be a vector rather than a single address? I'm okay with it being a vector so it gives us more flexibility, but I can't see the usecase clearly

**Comment by stiiifff** [comment]
@uditvira I went a bit further with the idea, see draft PR #240
